# Generated by Django 5.0.6 on 2025-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitarServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_id', models.IntegerField()),
                ('pessoa_id', models.IntegerField()),
                ('produto_id', models.IntegerField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
